### ISSUE TITLE
Misleading pages in documentation

### ISSUE THREAD

**Issue by Ceda-EI** [nextcloud/nextcloud.com#799] opened 2018-02-17 19:58 UTC
The following links in the docs are misleading as support for Google Drive and Dropbox has been removed.
* [Configuring External Storage (GUI)](https://docs.nextcloud.com/server/13/admin_manual/configuration_files/external_storage_configuration_gui.html#available-storage-backends): On this page in the available storage backends, Google Drive and Dropbox are listed but they are no longer available in NC 13.
* [Google Drive](https://docs.nextcloud.com/server/13/admin_manual/configuration_files/external_storage/google.html): Google Drive is no longer supported but the documentation makes no such claims.
* [Dropbox](https://docs.nextcloud.com/server/13/admin_manual/configuration_files/external_storage/dropbox.html): Dropbox is also unsupported but a page exists and does not say so.

**Comment by tflidd** [comment] 2018-02-18 11:07
duplicate of:
https://github.com/nextcloud/documentation/issues/669

**Closed by tflidd** 2018-02-18 11:07 UTC
