### ISSUE TITLE
Demo user on nextloud.com doesn't have passoword

### ISSUE THREAD

**Issue by urza** [nextcloud/nextcloud.com#1415] opened 2021-01-04 21:54 UTC
On https://try.nextcloud.com/ the "instat trial" login page has user name pregenerated but no password and it is not possible log in.

**Comment by jospoortvliet** [comment] 2021-01-27 17:09
the question is 'where'. It'd be great if it was right there on the login page, it would need a custom adaptation/app for that though. There is an app for that - https://apps.nextcloud.com/apps/login_notes so that might be a possible solution here. Let me ask internally.

**Comment by jospoortvliet** [comment] 2021-01-27 17:23
ah, duplicate of https://github.com/nextcloud-gmbh/demo-appliance/issues/16

**Closed by jospoortvliet** 2021-01-27 17:23 UTC
