### ISSUE TITLE
A background image is awfully made up.

### ISSUE THREAD

**Issue by Scottpedia** [nextcloud/nextcloud.com#1559] opened 2021-10-11 18:40 UTC
On the project's [web page](https://nextcloud.com/collaboraonline/), the background image shows a user on a Windows 10 operating system using Mozilla Firefox running in a Ubuntu GUI environment with no clear signs of a VM present. On the task bar, it's shown that only Skype and screenshot utility are opened. 

Well it's not really a serious error, but I don't think this kind of mistake is tolerable in the tech industry...

![screenshot](https://nextcloud.com/wp-content/themes/next/assets/img/headers/collabora.jpg?x53054)

**Comment by splitt3r** [comment] 2021-11-01 13:41
Duplicate of https://github.com/nextcloud/nextcloud.com/issues/1507

**Comment by acsfer** [comment] 2021-12-07 10:02
Closing as duplicate of https://github.com/nextcloud/nextcloud.com/issues/1507

**Closed by acsfer** 2021-12-07 10:02 UTC
